### ISSUE TITLE
fix typescript warnings

### ISSUE THREAD

**Issue by mechanoid** [Galeria-Kaufhof/stylegen#12]
this is for sure the thing that i really dislike on typescript, but we choose this lane so we should drive it to the end :)
- [ ] missing slug module definition
- [ ] missing btoa/atob mod definition
- [ ] missing remarkable mod definition
- [ ] fix array function call on union types `(string|string[])`
- [ ] duplicate promise def, because of double reference in nodeify lib
- [ ] nodeify signature fix

I know, it is a tedious task but lets fix these, or move away from typescript

**Comment by bdenham** [comment]
I'm having similar, if not the same, errors when I try to build from gulp: Lots of "Cannot find module 'xxxx'", so I've never been able to build it / use it. Is there a workaround I can use now?

**Comment by mechanoid** [comment]
The typescript errors, are merely warnings so the should not hinder you in building the project. So for the moment i just ignore these messages. (yeah, i know, but thats exactly the reason why i don't really like typescript that much)

**Comment by bdenham** [comment]
Ok, yes, I realize that now. Thanks for the extra help.

**Comment by mechanoid** [comment]
You're welcome. If you get in trouble lateron don't hesitate to ask or file a bug. The project is still in alpha mode, but we use it in a range of projects now, so that it will hopefully become better documented and more stable soon :)
